### ISSUE TITLE
read() requests caching in IE7

### ISSUE THREAD

**Issue by theirishpenguin** [alassek/jquery.rest#1]
Hi,

I find that GET requests are caching for me in IE7 when I try a $read against a resource. As a workaround I have changed the read() function in the jquery.rest code to be:

```
 function read () {
   collect_options.apply(this, arguments);
   $.extend(options, { type: 'GET' })
   $.extend(options, { cache: false }) // STOP IE CACHING
   return $.ajax(options);
 }
```

However, is there a way I can pass this { cache: false } into the $read() method from my calling code - instead of modifying the code in into jquery.rest framework? I see you mention the following in the README:

"In addition to these parameters, you can simply pass a standard jQuery.Ajax options object instead as the only parameter"

However, I want to just supress caching.

Thanks again for publishing jquery.rest. I find it quite useful.

Regards,
Declan

**Comment by theirishpenguin** [comment]
Ah, just answer my own question, you can move the { cache: false } parameter into the ajaxSetup() of your application.js. Might be nice to mention this briefly in your README.

This gives me the following ajaxSetup() function in my application.js:

<pre>
$.ajaxSetup({
  cache: false,
  beforeSend: function(xhr) {
    xhr.setRequestHeader("Accept", "text/javascript");
  }
});
</pre>

Regards,
Declan

**Comment by alassek** [comment]
Declan, thanks for your comments. I don't think this issue was related to my plugin, as I'm pretty certain you would have experienced the same issue with $.ajax, and the solution would have been the same.

You can attach a version number to resources as a query parameter to force a cache reset when it changes; I believe Rails does this for us, so we didn't experience this problem.

You are correct that changing this setting in ajaxSetup is the ideal place to do it.

If you have any other problems, feel free to let me know. I hope you find this plugin useful!
