### ISSUE TITLE
Using jquery.rest with inherited_resources

### ISSUE THREAD

**Issue by SachaG** [alassek/jquery.rest#9]
First, congratulations for writing a very useful plugin. I'm trying to use it in combination with inherited_resources, and although the "read" action works, "update" only returns an empty hash, even though I get a "success" 200 status code. 

How should I configure my controller to get it to work? Right now all I have is this:

```
class Admin::DesignersController < Admin::BaseController

  respond_to :html, :json

end
```

(with BaseController inheriting from inherited_resources)

**Comment by alassek** [comment]
Does the `$.update` command successfully change the data on the server? In that case it sounds like your controller simply isn't configured to return a value after a successful **update** action.

I'll take a look, but I don't know anything about `inherited_resources`. You'll need to separate the json and html response code, since html will usually redirect while json should return the updated record.

**Comment by alassek** [comment]
It looks like you want something like this:

``` ruby
class Admin::DesignersController < Admin::BaseController
  respond_to :html, :json

  def update
    update! do |format|
      format.html { redirect_to whatever_path }
      format.json do
        render :json => @designer
      end
    end
  end
end
```

I'm basing this off of the **Overwriting Actions** section of the [inherited_resources](https://github.com/josevalim/inherited_resources) README.

You'll need to fill in a few blanks there, but hopefully that should point you in the right direction. I'm closing this for now since it doesn't sound like an issue with `jQuery.rest` itself.

**Comment by SachaG** [comment]
Thanks a lot for your help, that did the trick!

The only reason why I thought it might've been a problem related to jQuery.rest was that I had a "success" response even though it didn't work. But it was not really a javascript problem after all.
